### PR TITLE
add ability for extra impl generics

### LINKED ISSUE #8: Support deriving traits with generic parameters
Given I have a trait with generic params:
 `Foo<T>`,
and a struct:
`Bar<Q>`

I want to be able to write a derive macro that transforms:

```rust
#[derive(Foo)]
struct Bar<Q> {
  field: Q,
  another_field: SomeCustomType
}
```

into:

```rust
impl<T ,Q> Foo<T> for Bar<Q>
  where Q: Foo<T>,
        SomeCustomType: Foo<T>,
{
  // implement trait methods here....
}
```

Currently, synstructure does nor alter (nor allow for alteration) of the generics within  `impl<>`. 
synstructure currently looks at the generics of the struct and inserts it as the `impl<>` generics without adding or removing any of them. This means that a trait with a different generic parameter will not be able to be derived.

### PR DESCRIPTION
**Pull request by nrxus**
Attempts to fix #8 

Mostly making a PR to start a conversation about it, I am totally okay with scrapping this and going in a different direction. 

Ideally I would like to expose more "intermediate" results, so that any user can add/remove stuff as they want, thus making the harder cases possible while still keeping the simple case easy. I am, however, unsure how to go about it just yet since I am not super used to procedural macros.

### CODE REVIEW

**Comment by mystor** [comment]
Thanks for the PR!

I think I'd also like to add support for adding new parameters to the gen_impl method. It'd be awesome if you could write:

```rust
s.gen_impl(quote! {
    extern crate krate;

    gen impl<U: krate::OtherTrait> krate::Trait<U> for @Self {
        fn f(&self) { ... }
    }
})
```

And get the trait bounds added implicitly :-)

**Comment by nrxus** [comment]
That's a good idea! I added the ability to do that. I modified the test for the gen_impl instead of adding a new test since it covers all the cases. Let me know if I should add a separate test case for when there are no generic parameters or if a single test that covers all the behavior is good enough.

**Comment by kngwyu** [comment]
I really love this PR and used `add_impl_generic` in [this PR](https://github.com/chucklefish/rlua/pull/75) to generate 
```rust
impl<'lua> ::rlua::IntoTable<'lua> for Struct {
...
}
```

Thank you @nrxus !

**Comment by nrxus** [comment]
@kngwyu I am glad this was useful to more than just me! (:

**Comment by mystor** [comment]
Thanks for the patch! I've also added support for `where` clauses, and this will be released in 0.7.1

**Pull request merged**
